spring:
  datasource:
    url: jdbc:mysql://localhost:3309/atrs_order_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: atrs123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Shanghai

# Seata
seata:
  tx-service-group: atrs-tx-group
  service:
    vgroup-mapping:
      atrs-tx-group: default
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      application: seata-server

logging:
  level:
    com.xxx.atrs: INFO
    io.seata: DEBUG
